name: Say Hello

on:
    push:
        branches:
            - main

jobs:
    hello-world:
        runs-on: ubuntu-latest

        steps:
            - name: Echo the message
              run: echo "Hello, World!"
            - name: Show the current date
              run: date
            - name: Show files in the current directory
              run: ls -l